import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, padding: 16 },
  card: { marginBottom: 16, elevation: 2 },
  title: { fontSize: 24 },
  plate: { fontSize: 16, marginTop: 4 },
  statusContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 12,
  },
  statusLabel: { fontSize: 16, marginRight: 8 },
  statusText: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
    fontSize: 14,
    fontWeight: "bold",
  },
  statusAvailable: { backgroundColor: "#e3f2fd", color: "#1976d2" },
  statusMaintenance: { backgroundColor: "#fff3e0", color: "#ef6c00" },
  statusRented: { backgroundColor: "#e3f2fd", color: "#1565c0" },
  statusOutOfService: { backgroundColor: "#ffebee", color: "#d32f2f" },
  sectionTitle: { fontSize: 18, marginBottom: 12 },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
    marginTop: 8,
  },
  infoLabel: { fontSize: 14 },
  infoValue: { fontSize: 14, fontWeight: "bold" },
  progressBar: { height: 8, borderRadius: 4, marginBottom: 16 },
  divider: { marginVertical: 12 },
  technicalInfoText: {
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
    marginBottom: 4,
    padding: 12,
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#1976d2',
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  statusButton: { flex: 1, marginHorizontal: 4 },
  availableButton: { backgroundColor: "#4CAF50" },
  maintenanceButton: { backgroundColor: "#ef6c00" },
  rentedButton: { backgroundColor: "#1565c0" },
  outOfServiceButton: { backgroundColor: "#d32f2f" },
  bottomButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
    marginBottom: 24,
  },
  button: { flex: 1, marginHorizontal: 4 },
});